export const ERROR_STATUS = {
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INTERNAL_DB_ERROR: 'INTERNAL_DB_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED'
};

export const STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  PENDING: 'pending',
  DELETED: 'deleted'
};
